---
abstract: 'Stop CPAN from indexing stuff'
author:
  - 'Mark Gardner <MJGARDNER@cpan.org>'
  - 'JT Smith <RIZEN@cpan.org>'
build_requires:
  Cwd: 0
  Data::PowerSet: 0
  Dist::Zilla::Tester: 4.101550
  File::Find: 0
  File::Temp: 0
  Modern::Perl: 0
  Path::Class: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  Text::Template: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101550, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MetaNoIndex
requires:
  Dist::Zilla::Role::MetaProvider: 4.101550
  English: 0
  Moose: 0
  Readonly: 0
  perl: 5.010
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-MetaNoIndex
  repository: http://github.com/mjg/Dist-Zilla-Plugin-MetaNoIndex
version: 1.101550
