---
abstract: 'Stop CPAN from indexing stuff'
author:
  - 'JT Smith <RIZEN@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MetaNoIndex
requires:
  Config::MVP: 0.100780
  Dist::Zilla: 1.093400
version: 0.0300
